# Site settings
title: Gitanshu Munjal
description: |
  <i>my life in a quote (...well 3 actually)</i>
  
          Mickey: Your nose is broke

                            Rocky: How does it look?
  
          Mickey: It's an improvement...
owner: Gitanshu Munjal
first_published: 2016 
email: grmunjal@gmail.com
baseurl: "" 
url: "grmunjal.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/grmunjal
  github: https://github.com/grmunjal
  linkedin-square: http://www.linkedin.com/pub/gitanshu-munjal/41/65/533
  email: "mailto:grmunjal@gmail.com"


# Build settings
markdown: kramdown

#sass:
#  style: compressed

gems:
  - jekyll-sitemap